# Adapted from https://realpython.com/lessons/logger-config-file/

[loggers]
keys=root,fileLogger,multiLogger

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=fileFormatter,consoleFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler

# This logger only writes to the log file
[logger_fileLogger]
level=DEBUG
handlers=fileHandler
qualname=fileLogger
propagate=0

# This logger writes to the console (print statements) and the log file
[logger_multiLogger]
level=INFO
handlers=fileHandler,consoleHandler
qualname=multiLogger
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=consoleFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=fileFormatter
args=(r'logging\cga_script.log', 'w')

[formatter_fileFormatter]
format='%(asctime)s - Line: %(lineno)4d - %(levelname)8s - Func: %(funcName)25s - %(message)s'

[formatter_consoleFormatter]
format='%(asctime)s - %(message)s'